# --- ADHOCTD specific parameters ---
name: "adhoc_td"
common_reward: False
standardise_rewards: False
action_selector: "epsilon_greedy"
runner: "parallel"
batch_size_run: 1
buffer_size: 10000
batch_size: 32
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
obs_agent_id: False 
obs_last_action: True 
# use the Q_Learner to train
mac: "n_mac_adhoctd"
shared_agent: False
start_advice: 250000
budget: 50000
variable_a: 0.5
variable_g: 1.5
agent: "n_rnn_ns"
agent_output_type: "q"
# update the target network every {} episodes
target_update_interval: 200
learner: "nq_learner"
mixer:
# network
mixing_embed_dim: 32
hypernet_embed: 64
lr: 0.001
td_lambda: 0
optimizer: 'adam'
optim_alpha: 0.99
optim_eps: 0.00000001
use_layer_norm: False
use_orthogonal: False
gain: 0.01