env: "gymma"

env_args:
  key: null
  time_limit: 25
  pretrained_wrapper: null

# env
t_max: 5050000
test_greedy: True
test_nepisode: 64
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
save_model_interval: 1000000
